server:
  port: 8080

spring:
  application:
    name: log
  redis:
    host: 192.168.1.152
    port: 6379
    database: 1
  jedis:
    pool:
      max-active: 10
      min-idle: 5
      max-wait: -1
      time-between-eviction-runs: 1000
      max-idle: 30
